#!groovy
pipeline {
  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
  }
  agent any
   parameters{ 
    text(name: 'mvn_arg', defaultValue: true, description: 'This is to input maven argument')
}
  stages {
    stage('Build') {
      steps {
        script {
          sh '''
            SBI/build.sh
          '''
        }
      }
    }
    stage('Test') {
      post {
        always {
          //cucumber report generation step
          step([
               $class: 'CucumberReportPublisher',
	             fileIncludePattern: '**/*.json',
               jsonReportDirectory: 'target/execution-surefire-reports'
	      ])
        }
      }
      steps {
        script {
          sh '''
            SBI/test.sh
          '''
        }
      }
    }
  }
  post {
    always {
      script {
        currentBuild.result = currentBuild.currentResult
        deleteDir()
      }
    }
    fixed {
      emailext (attachLog: true, body: "${currentBuild.result}: ${BUILD_URL}", compressLog: true, 
                subject: "Jenkins build back to normal: ${currentBuild.fullDisplayName}", 
                recipientProviders: [[$class: 'CulpritsRecipientProvider'],[$class: 'RequesterRecipientProvider']],
                to: 'RCXQA@rythmos.com')
    }
    failure {
      // notify users when the Pipeline fails
      emailext (attachLog: true,
                body: "${currentBuild.result}: ${BUILD_URL}", compressLog: true, 
                subject: "Build failed in Jenkins: ${currentBuild.fullDisplayName}", 
              //  recipientProviders: [[$class: 'CulpritsRecipientProvider'],[$class: 'RequesterRecipientProvider']],
                to: 'smandal@rythmos.com')
    }
    unstable {
      // notify users when the Pipeline unstable
      emailext (attachLog: true, body: "${currentBuild.result}: ${BUILD_URL}", compressLog: true, 
                subject: "Unstable Pipeline: ${currentBuild.fullDisplayName}", 
               // recipientProviders: [[$class: 'CulpritsRecipientProvider'],[$class: 'RequesterRecipientProvider']],
                to: 'smandal@rythmos.com')
    }
  }
}
